### ISSUE TITLE
Issue with Results and error handling

### ISSUE THREAD

**Issue by kilroyjones** [mbenoukaiss/automate#3]
Really handy library, so thanks for creating it. I had tried serenity but it doesn't play well with async stuff. 

I had some issues with getting errors to line up in my Results. Within a listener I was making calls to an async function which returned a Box<dyn std::error::Error>. To get the automatic conversion to work properly I had to modify the **error.rs** file as follows: 

`impl<T: std::error::Error> From<T> for Error {
      fn from(e: T) -> Error {
          Error::new(e.to_string())
      }   
  }`

In the process I removed error handling from **hyper::error** down to get it work. There may be some better way to do it, but after consulting the rust channel on discord the above seemed to be the cleanest and easiest.

**Comment by mbenoukaiss** [comment]
Thank you!

Indeed it's actually a better way to do it since many if not all of the errors implement `std::error::Error` anyway so it'll reduce the amount of code and improve compatibility.
The way I implement the library's  Error type can probably be improved in other ways, I should make it an enum to provide more info to the user.  I'll try to make these changes during the next week.

**Comment by mbenoukaiss** [comment]
I've updated master with the new error implementation.
The only thing is I can not implement `std::error::Error` on `automate::Error` because of the `From<std::error::Error>` now, but that should not be a problem.

Thank you for your contribution! You can use the updated version with:
`automate = { git = "https://github.com/mbenoukaiss/automate", hash = "384146c" }`
